language: node_js

node_js:
  - node

sudo: required

before_install:
  - yarn add coveralls

script:
  - yarn run test
  - yarn run build

after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - travis@plusnew.io
    on_success: change
    on_failure: always
